version: "2"
services:
    api:
        image: lewdcpthoopes/zombie-rp-server
        build: .
        ports:
            - "8000:8000"
        depends_on:
            - mongo
    mongo:
        image: mongo
        ports:
            - "27017:27017"
